### ISSUE TITLE
Ask about the source code

### ISSUE THREAD

**Issue by ducnguyen201203** [Delong-liu-bupt/SEN#1]
hi, I am a graduate student working on text-to-image person re-identification, and I have read your paper "Unleashing the Imagination of Text: A Novel Framework for Text-to-image Person Retrieval via Exploring the Power of Words" with great interest. 

Can you show me the source code please?

**Comment by Delong-liu-bupt** [comment]
Apologies for the delay. The code is now available, and the model will be released soon.
